version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - nginx-demo-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - nginx-demo-network
    environment:
      - PYTHONUNBUFFERED=1

networks:
  nginx-demo-network:
    driver: bridge